# ==========================
# Stage: Development
# ==========================
FROM node:22-alpine

WORKDIR /app

# Instalar dependencias del sistema necesarias para Prisma
RUN apk add --no-cache openssl

# Copiar archivos de configuración
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el código fuente
COPY . .

# Exponer el puerto del backend
EXPOSE 3000

# Comando por defecto en modo desarrollo
CMD ["npm", "run", "start:dev"]
