FROM node:22-alpine

WORKDIR /app

# Instala dependencias globales necesarias
RUN apk add --no-cache openssl

# Copia solo package.json primero
COPY package*.json ./

# Instala dependencias (node_modules se instala dentro del contenedor)
RUN npm install

# Copia el resto del código
COPY . .

# Generar Prisma client DENTRO del contenedor
RUN npx prisma generate

CMD ["npm", "run", "start:dev"]
